package handler

import (
	"bytes"
	"encoding/json"
	"image/png"
	"io"
	"net/http"
	"net/http/httptest"
	"net/url"
	"strings"
	"testing"

	"github.com/gin-gonic/gin"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

type responseEnvelope struct {
	Data  string `json:"data"`
	Error string `json:"error"`
}

func newTestRouter() *gin.Engine {
	gin.SetMode(gin.TestMode)
	gin.DefaultWriter = io.Discard
	r := gin.New()
	Route(r)
	return r
}

func TestFrontendRoutes(t *testing.T) {
	r := newTestRouter()
	pages := append([]string{"/"}, toolPagePaths...)

	for _, path := range pages {
		t.Run(path, func(t *testing.T) {
			w := httptest.NewRecorder()
			req := httptest.NewRequest(http.MethodGet, path, nil)
			r.ServeHTTP(w, req)

			assert.Equal(t, http.StatusOK, w.Code)
			assert.Contains(t, w.Header().Get("Content-Type"), "text/html")
			assert.Contains(t, w.Body.String(), "GOTL")
			assert.Contains(t, w.Body.String(), `id="app"`)
		})
	}
}

func TestFrontendShellLinksAndRunStatus(t *testing.T) {
	r := newTestRouter()
	w := httptest.NewRecorder()
	req := httptest.NewRequest(http.MethodGet, "/", nil)
	r.ServeHTTP(w, req)

	require.Equal(t, http.StatusOK, w.Code)
	body := w.Body.String()
	assert.Contains(t, body, `href="https://github.com/pigjin/gotl"`)
	assert.Contains(t, body, `target="_blank"`)
	assert.Contains(t, body, `rel="noopener noreferrer"`)
	assert.NotContains(t, body, "本地运行")
	assert.NotContains(t, body, "localhost:8080")
}

func TestFrontendAssets(t *testing.T) {
	r := newTestRouter()
	tests := []struct {
		path     string
		contains string
	}{
		{path: "/assets/styles.css", contains: ":root"},
		{path: "/assets/app.js", contains: "const tools"},
		{path: "/assets/i18n.js", contains: "createLanguageController"},
		{path: "/assets/theme.js", contains: "createThemeController"},
		{path: "/assets/json-format.js", contains: "GOTLJSON"},
		{path: "/assets/vendor/json-to-go.js", contains: "function jsonToGo"},
	}

	for _, tt := range tests {
		t.Run(tt.path, func(t *testing.T) {
			w := httptest.NewRecorder()
			req := httptest.NewRequest(http.MethodGet, tt.path, nil)
			r.ServeHTTP(w, req)

			assert.Equal(t, http.StatusOK, w.Code)
			assert.Contains(t, w.Body.String(), tt.contains)
		})
	}
}

func TestFrontendIconReferences(t *testing.T) {
	r := newTestRouter()
	w := httptest.NewRecorder()
	req := httptest.NewRequest(http.MethodGet, "/", nil)
	r.ServeHTTP(w, req)

	require.Equal(t, http.StatusOK, w.Code)
	body := w.Body.String()
	assert.Contains(t, body, `href="/assets/favicon-32.png"`)
	assert.Contains(t, body, `href="/assets/apple-touch-icon-180.png"`)
	assert.Contains(t, body, `src="/assets/gotl-icon-128.png"`)
}

func TestFrontendIconAssets(t *testing.T) {
	r := newTestRouter()
	tests := []struct {
		path   string
		width  int
		height int
	}{
		{path: "/assets/gotl-icon-1024.png", width: 1024, height: 1024},
		{path: "/assets/gotl-icon-128.png", width: 128, height: 128},
		{path: "/assets/favicon-32.png", width: 32, height: 32},
		{path: "/assets/apple-touch-icon-180.png", width: 180, height: 180},
	}

	for _, tt := range tests {
		t.Run(tt.path, func(t *testing.T) {
			w := httptest.NewRecorder()
			req := httptest.NewRequest(http.MethodGet, tt.path, nil)
			r.ServeHTTP(w, req)

			require.Equal(t, http.StatusOK, w.Code)
			assert.Equal(t, "image/png", w.Header().Get("Content-Type"))
			require.NotEmpty(t, w.Body.Bytes())
			config, err := png.DecodeConfig(bytes.NewReader(w.Body.Bytes()))
			require.NoError(t, err)
			assert.Equal(t, tt.width, config.Width)
			assert.Equal(t, tt.height, config.Height)
		})
	}
}

func TestUnknownToolRouteReturnsNotFound(t *testing.T) {
	r := newTestRouter()
	w := httptest.NewRecorder()
	req := httptest.NewRequest(http.MethodGet, "/tools/unknown", nil)
	r.ServeHTTP(w, req)

	assert.Equal(t, http.StatusNotFound, w.Code)
}

func TestConversionEndpoints(t *testing.T) {
	r := newTestRouter()
	ddl := "CREATE TABLE users (id BIGINT NOT NULL AUTO_INCREMENT, name VARCHAR(64) NOT NULL, PRIMARY KEY (id));"
	tests := []struct {
		name     string
		path     string
		form     url.Values
		contains string
	}{
		{name: "sql to ent", path: "/sql2ent", form: url.Values{"ddl": {ddl}}, contains: "type Users struct"},
		{name: "sql to gorm", path: "/sql2gorm", form: url.Values{"ddl": {ddl}}, contains: "package model"},
		{name: "sql to go-zero", path: "/sql2gozero", form: url.Values{"ddl": {ddl}, "cache": {"0"}}, contains: "UsersModel interface"},
		{name: "sql to es", path: "/sql2es", form: url.Values{"schema": {"SELECT * FROM users WHERE status = 'active'"}}, contains: `"query"`},
		{name: "yaml to go", path: "/yaml2go", form: url.Values{"schema": {"name: gotl\nenabled: true\n"}}, contains: "type AutoGenerated struct"},
		{name: "yaml to json", path: "/yaml2json", form: url.Values{"schema": {"name: gotl\nenabled: true\nports:\n  - 8080\n  - 8081\n"}}, contains: `"name":"gotl"`},
		{name: "xml to json", path: "/xml2json", form: url.Values{"schema": {"<tool><name>gotl</name></tool>"}}, contains: `"tool"`},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			payload := performFormRequest(t, r, tt.path, tt.form)
			require.Empty(t, payload.Error)
			assert.Contains(t, payload.Data, tt.contains)
		})
	}
}

func TestConversionEndpointErrors(t *testing.T) {
	r := newTestRouter()
	tests := []struct {
		name string
		path string
		form url.Values
	}{
		{name: "sql to ent", path: "/sql2ent", form: url.Values{"ddl": {"CREATE TABLE"}}},
		{name: "sql to gorm", path: "/sql2gorm", form: url.Values{"ddl": {"CREATE TABLE"}}},
		{name: "sql to go-zero", path: "/sql2gozero", form: url.Values{"ddl": {"CREATE TABLE"}, "cache": {"0"}}},
		{name: "sql to es", path: "/sql2es", form: url.Values{"schema": {"SELECT FROM"}}},
		{name: "yaml to go", path: "/yaml2go", form: url.Values{"schema": {"broken: ["}}},
		{name: "yaml to json", path: "/yaml2json", form: url.Values{"schema": {"broken: ["}}},
		{name: "xml to json", path: "/xml2json", form: url.Values{"schema": {"<tool>\x00</tool>"}}},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			payload := performFormRequest(t, r, tt.path, tt.form)
			assert.NotEmpty(t, payload.Error)
		})
	}
}

func TestYamlToJSON(t *testing.T) {
	tests := []struct {
		name     string
		schema   string
		expected interface{}
	}{
		{
			name:     "nested object and array",
			schema:   "app:\n  name: gotl\n  enabled: true\nports:\n  - 8080\n  - 8081\n",
			expected: map[string]interface{}{"app": map[string]interface{}{"name": "gotl", "enabled": true}, "ports": []interface{}{float64(8080), float64(8081)}},
		},
		{
			name:     "top-level scalar",
			schema:   "gotl\n",
			expected: "gotl",
		},
		{
			name:     "top-level array",
			schema:   "- converter\n- formatter\n",
			expected: []interface{}{"converter", "formatter"},
		},
		{
			name:     "anchor and alias",
			schema:   "defaults: &defaults\n  enabled: true\napp: *defaults\n",
			expected: map[string]interface{}{"defaults": map[string]interface{}{"enabled": true}, "app": map[string]interface{}{"enabled": true}},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			actual, err := convertYAMLToJSON(tt.schema)
			require.NoError(t, err)
			assert.NotContains(t, actual, "\n")

			var decoded interface{}
			require.NoError(t, json.Unmarshal([]byte(actual), &decoded))
			assert.Equal(t, tt.expected, decoded)
		})
	}
}

func TestYamlToJSONErrors(t *testing.T) {
	tests := []struct {
		name   string
		schema string
	}{
		{name: "empty", schema: "  \n"},
		{name: "invalid", schema: "broken: ["},
		{name: "multiple documents", schema: "name: first\n---\nname: second\n"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			_, err := convertYAMLToJSON(tt.schema)
			assert.Error(t, err)
		})
	}
}

func performFormRequest(t *testing.T, r http.Handler, path string, form url.Values) responseEnvelope {
	t.Helper()
	w := httptest.NewRecorder()
	req := httptest.NewRequest(http.MethodPost, path, strings.NewReader(form.Encode()))
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	r.ServeHTTP(w, req)

	require.Equal(t, http.StatusOK, w.Code)
	var payload responseEnvelope
	require.NoError(t, json.Unmarshal(w.Body.Bytes(), &payload))
	return payload
}
